sign up page
csirianni/private-data-lookup pull request #1
Opened 2023-10-03 22:18 UTC by ni-jessica

<img width="1073" alt="image" src="https://github.com/csirianni/private-data-lookup/assets/98488267/6981313d-8f42-44b6-bca5-042daf9041c7">

2023-10-03 22:55 UTC, csirianni requested changes
**issue**: Use [conventional commit messages](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13). In the case, the message could be 
> feat: implement simple sign up page

Don't overwrite the commit history, just add a new commit that changes the previous message. 

Also, I'm using [conventional comments ](https://conventionalcomments.org/) for PR reviews :)

2023-10-03 22:55 UTC, csirianni commented on frontend/README.md
> +made with next.js
**question**: Why did you choose NextJS over React? I know that NextJS is a superset of React, just curious about your choice.

2023-10-03 22:55 UTC, csirianni commented on frontend/app/page.tsx
> +              </Grid>
**issue**: We don't have a privacy policy. Can we just remove this?

2023-10-03 22:55 UTC, csirianni commented on frontend/app/page.tsx
> +}
**suggestion**: Remove this component because we don't have a copyright. Alternatively, link to the MIT license in the GitHub repo.

2023-10-04 01:21 UTC, csirianni commented on frontend/app/page.tsx
> +import Link from "@mui/material/Link";
**issue**: Remove unused import.

2023-10-05 18:06 UTC, stellaljung approved these changes

2023-10-05 18:08 UTC, merged