feat: update webpage based on get request
csirianni/private-data-lookup pull request #11
Opened 2023-10-06 15:46 UTC by ni-jessica

2023-10-06 16:11 UTC, stellaljung submitted a review, later dismissed

2023-10-07 18:06 UTC, csirianni requested changes

2023-10-08 15:57 UTC, ni-jessica commented on frontend/app/page.tsx
> +  const Alert = forwardRef<HTMLDivElement, AlertProps>(function Alert(
react is picky about syntax, it has to be uppercase if its a rendered component

2023-10-08 16:44 UTC, csirianni approved these changes
Nice job! I didn't realize that `forwardRef` renders a component. Haven't seen that syntax before.

2023-10-09 20:07 UTC, stellaljung approved these changes

2023-10-09 20:08 UTC, merged