feat: add checkmarks for satisfied password requirements
csirianni/private-data-lookup pull request #26
Opened 2023-10-29 22:07 UTC by ni-jessica

2023-10-29 22:10 UTC, ni-jessica commented
https://github.com/csirianni/private-data-lookup/assets/98488267/beeb5e5a-2eef-414a-a6ec-37109d1bbd07

Ignore the error I wasn't running backend lol

2023-11-01 16:42 UTC, stellaljung requested changes

2023-11-01 16:42 UTC, stellaljung commented on frontend/app/page.tsx
> +                                        specialChar: "Password has a special character.",
**question**: Do we want to list the special characters that can be used here that match our password regex? So "!#$%&()*+,-./:;<=>?@[]^_`{|}~"

2023-11-01 16:42 UTC, stellaljung commented on frontend/app/page.tsx
> +                                <PasswordChecklist
**praise**: Good use of react components! It makes the code so clean and easy to read.

2023-11-03 15:47 UTC, stellaljung approved these changes

2023-11-03 15:47 UTC, merged

2023-12-24 22:16 UTC, csirianni commented
<img width="1352" alt="Screenshot 2023-12-24 at 5 16 09 PM" src="https://github.com/csirianni/private-data-lookup/assets/54677998/d57e9890-6ab3-423f-a7d5-cdf97a930296">