19 compute set intersection
csirianni/private-data-lookup pull request #27
Opened 2023-11-01 16:28 UTC by stellaljung

Please review the test formatting. I included the testing in the main.cpp file due to this [Crow testing tutorial](https://crowcpp.org/master/guides/testing/). I only tested response codes in the backend because there was not enough detail in the Crow framework of how to get the body of the request. If there is a better way of catch/throwing vs cout/cerr please add in the pull request.

2023-11-02 16:01 UTC, csirianni requested changes
Commit messages look amazing!!! Thanks so much.

2023-11-03 15:05 UTC, stellaljung commented on frontend/app/handlers.ts
> +            body: password
Changing body to be a JSON object will be a later issue when we have multiple things sent in the json body request, but for now body is standard for the fetch API and can not be changed.

2023-11-03 19:30 UTC, ni-jessica approved these changes

2023-11-03 19:30 UTC, ni-jessica commented on backend/test/password.cpp
> +#include "password.hpp"
**question**: I'm wondering why this doesn't need relative import.

2023-11-03 19:32 UTC, ni-jessica commented on backend/test/password.cpp
> +#include "password.hpp"
nevermind i just didn't read the group chat, i get it now!

2023-11-03 20:57 UTC, csirianni approved these changes

2023-11-04 03:43 UTC, merged